import type { Metadata } from "next";
import { Lora, Open_Sans } from "next/font/google";
import "startbootstrap-clean-blog/dist/css/styles.css";
import "../../node_modules/highlight.js/styles/vs2015.css";
import "./globals.css";
import { MainNavigation } from "@/components/layout/mainNavigation";
import { Footer } from "@/components/layout/footer";
import { getPage } from "@/lib/umbraco";
import { HomeContentResponseModel } from "@/lib/api/model";

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700', '800'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { config } from '@fontawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const homePage = await getPage<HomeContentResponseModel>("");

  return (
    <html lang="en">
      <body className={`${lora.className} ${openSans.className}`}>
        <MainNavigation homePage={homePage} />
        {children}
        <Footer homePage={homePage} />
      </body>
    </html>
  );
}