/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type {
  GetContent20400,
  GetContent20Params,
  GetContentItemById20Params,
  GetContentItemByPath20Params,
  GetContentItems20Params,
  IApiContentResponseModel,
  PagedIApiContentResponseModel
} from '.././model';

import { customFetch } from '../../../custom-fetch';

export type getContent20Response200 = {
  data: PagedIApiContentResponseModel
  status: 200
}

export type getContent20Response400 = {
  data: GetContent20400
  status: 400
}

export type getContent20Response404 = {
  data: void
  status: 404
}
    
export type getContent20ResponseSuccess = (getContent20Response200) & {
  headers: Headers;
};
export type getContent20ResponseError = (getContent20Response400 | getContent20Response404) & {
  headers: Headers;
};

export type getContent20Response = (getContent20ResponseSuccess | getContent20ResponseError)

export const getGetContent20Url = (params?: GetContent20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["filter","sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/content?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/content`
}

export const getContent20 = async (params?: GetContent20Params, options?: RequestInit): Promise<getContent20Response> => {
  
  return customFetch<getContent20Response>(getGetContent20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItemByPath20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemByPath20Response401 = {
  data: void
  status: 401
}

export type getContentItemByPath20Response403 = {
  data: void
  status: 403
}

export type getContentItemByPath20Response404 = {
  data: void
  status: 404
}
    
export type getContentItemByPath20ResponseSuccess = (getContentItemByPath20Response200) & {
  headers: Headers;
};
export type getContentItemByPath20ResponseError = (getContentItemByPath20Response401 | getContentItemByPath20Response403 | getContentItemByPath20Response404) & {
  headers: Headers;
};

export type getContentItemByPath20Response = (getContentItemByPath20ResponseSuccess | getContentItemByPath20ResponseError)

export const getGetContentItemByPath20Url = (path: string,
    params?: GetContentItemByPath20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/content/item/${path}?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/content/item/${path}`
}

export const getContentItemByPath20 = async (path: string,
    params?: GetContentItemByPath20Params, options?: RequestInit): Promise<getContentItemByPath20Response> => {
  
  return customFetch<getContentItemByPath20Response>(getGetContentItemByPath20Url(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItemById20Response200 = {
  data: IApiContentResponseModel
  status: 200
}

export type getContentItemById20Response401 = {
  data: void
  status: 401
}

export type getContentItemById20Response403 = {
  data: void
  status: 403
}

export type getContentItemById20Response404 = {
  data: void
  status: 404
}
    
export type getContentItemById20ResponseSuccess = (getContentItemById20Response200) & {
  headers: Headers;
};
export type getContentItemById20ResponseError = (getContentItemById20Response401 | getContentItemById20Response403 | getContentItemById20Response404) & {
  headers: Headers;
};

export type getContentItemById20Response = (getContentItemById20ResponseSuccess | getContentItemById20ResponseError)

export const getGetContentItemById20Url = (id: string,
    params?: GetContentItemById20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/content/item/${id}?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/content/item/${id}`
}

export const getContentItemById20 = async (id: string,
    params?: GetContentItemById20Params, options?: RequestInit): Promise<getContentItemById20Response> => {
  
  return customFetch<getContentItemById20Response>(getGetContentItemById20Url(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getContentItems20Response200 = {
  data: IApiContentResponseModel[]
  status: 200
}

export type getContentItems20Response401 = {
  data: void
  status: 401
}

export type getContentItems20Response403 = {
  data: void
  status: 403
}
    
export type getContentItems20ResponseSuccess = (getContentItems20Response200) & {
  headers: Headers;
};
export type getContentItems20ResponseError = (getContentItems20Response401 | getContentItems20Response403) & {
  headers: Headers;
};

export type getContentItems20Response = (getContentItems20ResponseSuccess | getContentItems20ResponseError)

export const getGetContentItems20Url = (params?: GetContentItems20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["id"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/content/items?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/content/items`
}

export const getContentItems20 = async (params?: GetContentItems20Params, options?: RequestInit): Promise<getContentItems20Response> => {
  
  return customFetch<getContentItems20Response>(getGetContentItems20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


