/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type {
  GetMedia20400,
  GetMedia20Params,
  GetMediaItemById20Params,
  GetMediaItemByPath20Params,
  GetMediaItems20Params,
  IApiMediaWithCropsResponseModel,
  PagedIApiMediaWithCropsResponseModel
} from '.././model';

import { customFetch } from '../../../custom-fetch';

export type getMedia20Response200 = {
  data: PagedIApiMediaWithCropsResponseModel
  status: 200
}

export type getMedia20Response400 = {
  data: GetMedia20400
  status: 400
}
    
export type getMedia20ResponseSuccess = (getMedia20Response200) & {
  headers: Headers;
};
export type getMedia20ResponseError = (getMedia20Response400) & {
  headers: Headers;
};

export type getMedia20Response = (getMedia20ResponseSuccess | getMedia20ResponseError)

export const getGetMedia20Url = (params?: GetMedia20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["filter","sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/media?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/media`
}

export const getMedia20 = async (params?: GetMedia20Params, options?: RequestInit): Promise<getMedia20Response> => {
  
  return customFetch<getMedia20Response>(getGetMedia20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getMediaItemByPath20Response200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemByPath20Response404 = {
  data: void
  status: 404
}
    
export type getMediaItemByPath20ResponseSuccess = (getMediaItemByPath20Response200) & {
  headers: Headers;
};
export type getMediaItemByPath20ResponseError = (getMediaItemByPath20Response404) & {
  headers: Headers;
};

export type getMediaItemByPath20Response = (getMediaItemByPath20ResponseSuccess | getMediaItemByPath20ResponseError)

export const getGetMediaItemByPath20Url = (path: string,
    params?: GetMediaItemByPath20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/media/item/${path}?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/media/item/${path}`
}

export const getMediaItemByPath20 = async (path: string,
    params?: GetMediaItemByPath20Params, options?: RequestInit): Promise<getMediaItemByPath20Response> => {
  
  return customFetch<getMediaItemByPath20Response>(getGetMediaItemByPath20Url(path,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getMediaItemById20Response200 = {
  data: IApiMediaWithCropsResponseModel
  status: 200
}

export type getMediaItemById20Response404 = {
  data: void
  status: 404
}
    
export type getMediaItemById20ResponseSuccess = (getMediaItemById20Response200) & {
  headers: Headers;
};
export type getMediaItemById20ResponseError = (getMediaItemById20Response404) & {
  headers: Headers;
};

export type getMediaItemById20Response = (getMediaItemById20ResponseSuccess | getMediaItemById20ResponseError)

export const getGetMediaItemById20Url = (id: string,
    params?: GetMediaItemById20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/media/item/${id}?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/media/item/${id}`
}

export const getMediaItemById20 = async (id: string,
    params?: GetMediaItemById20Params, options?: RequestInit): Promise<getMediaItemById20Response> => {
  
  return customFetch<getMediaItemById20Response>(getGetMediaItemById20Url(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


export type getMediaItems20Response200 = {
  data: IApiMediaWithCropsResponseModel[]
  status: 200
}
    
export type getMediaItems20ResponseSuccess = (getMediaItems20Response200) & {
  headers: Headers;
};
;

export type getMediaItems20Response = (getMediaItems20ResponseSuccess)

export const getGetMediaItems20Url = (params?: GetMediaItems20Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["id"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:5100/umbraco/delivery/api/v2/media/items?${stringifiedParams}` : `http://localhost:5100/umbraco/delivery/api/v2/media/items`
}

export const getMediaItems20 = async (params?: GetMediaItems20Params, options?: RequestInit): Promise<getMediaItems20Response> => {
  
  return customFetch<getMediaItems20Response>(getGetMediaItems20Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


