/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { ContentContentModel } from './contentContentModel';
import type { ContentContentResponseModelContentType } from './contentContentResponseModelContentType';

export type ContentContentResponseModel = Omit<IApiContentResponseModelBase & ContentContentModel, 'contentType'> & {
  contentType: ContentContentResponseModelContentType;
};
