/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { HidePropertyPropertiesModel } from './hidePropertyPropertiesModel';
import type { HidePropertyElementModelContentType } from './hidePropertyElementModelContentType';

export type HidePropertyElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: HidePropertyPropertiesModel;
  contentType: HidePropertyElementModelContentType;
};
