/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { ApiContentRouteModel } from './apiContentRouteModel';
import type { IApiContentResponseModelBaseCultures } from './iApiContentResponseModelBaseCultures';

export type IApiContentResponseModelBase = Omit<IApiContentModelBase, 'contentType'> & {
  readonly id: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate: string;
  readonly updateDate: string;
  readonly route: ApiContentRouteModel;
  readonly cultures: IApiContentResponseModelBaseCultures;
} & Required<Pick<Omit<IApiContentModelBase, 'contentType'> & {
  readonly id: string;
  readonly contentType: string;
  /** @nullable */
  readonly name?: string | null;
  readonly createDate: string;
  readonly updateDate: string;
  readonly route: ApiContentRouteModel;
  readonly cultures: IApiContentResponseModelBaseCultures;
}, 'cultures'>>;
