/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ArticleControlsContentModel } from './articleControlsContentModel';
import type { CategoryContentModel } from './categoryContentModel';
import type { ContactFormControlsContentModel } from './contactFormControlsContentModel';
import type { ContentControlsContentModel } from './contentControlsContentModel';
import type { FooterControlsContentModel } from './footerControlsContentModel';
import type { HeaderControlsContentModel } from './headerControlsContentModel';
import type { MainImageControlsContentModel } from './mainImageControlsContentModel';
import type { SEocontrolsContentModel } from './sEocontrolsContentModel';
import type { VisibilityControlsContentModel } from './visibilityControlsContentModel';
import type { HomeContentModel } from './homeContentModel';
import type { ArticleContentModel } from './articleContentModel';
import type { ArticleListContentModel } from './articleListContentModel';
import type { AuthorContentModel } from './authorContentModel';
import type { AuthorListContentModel } from './authorListContentModel';
import type { CategoryListContentModel } from './categoryListContentModel';
import type { ContactContentModel } from './contactContentModel';
import type { ContentContentModel } from './contentContentModel';
import type { ErrorContentModel } from './errorContentModel';
import type { SearchContentModel } from './searchContentModel';
import type { XMlsitemapContentModel } from './xMlsitemapContentModel';

export type IApiContentModel = ArticleControlsContentModel | CategoryContentModel | ContactFormControlsContentModel | ContentControlsContentModel | FooterControlsContentModel | HeaderControlsContentModel | MainImageControlsContentModel | SEocontrolsContentModel | VisibilityControlsContentModel | HomeContentModel | ArticleContentModel | ArticleListContentModel | AuthorContentModel | AuthorListContentModel | CategoryListContentModel | ContactContentModel | ContentContentModel | ErrorContentModel | SearchContentModel | XMlsitemapContentModel;
