/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type ImageCarouselRowElementModelContentType = typeof ImageCarouselRowElementModelContentType[keyof typeof ImageCarouselRowElementModelContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageCarouselRowElementModelContentType = {
  imageCarouselRow: 'imageCarouselRow',
} as const;
