/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { ImageRowSettingsPropertiesModel } from './imageRowSettingsPropertiesModel';
import type { ImageRowSettingsElementModelContentType } from './imageRowSettingsElementModelContentType';

export type ImageRowSettingsElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: ImageRowSettingsPropertiesModel;
  contentType: ImageRowSettingsElementModelContentType;
};
