/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ImageCropCoordinatesModel } from './imageCropCoordinatesModel';

export interface ImageCropModel {
  /** @nullable */
  alias?: string | null;
  width: number;
  height: number;
  coordinates?: ImageCropCoordinatesModel;
}
