/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { SEocontrolsPropertiesModel } from './sEocontrolsPropertiesModel';
import type { SEocontrolsContentModelContentType } from './sEocontrolsContentModelContentType';

export type SEocontrolsContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: SEocontrolsPropertiesModel;
  contentType: SEocontrolsContentModelContentType;
};
