/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ArticleControlsPropertiesModel } from './articleControlsPropertiesModel';
import type { ContentControlsPropertiesModel } from './contentControlsPropertiesModel';
import type { HeaderControlsPropertiesModel } from './headerControlsPropertiesModel';
import type { ListPageSettingsPropertiesModel } from './listPageSettingsPropertiesModel';
import type { MainImageControlsPropertiesModel } from './mainImageControlsPropertiesModel';
import type { SEocontrolsPropertiesModel } from './sEocontrolsPropertiesModel';
import type { VisibilityControlsPropertiesModel } from './visibilityControlsPropertiesModel';

export type ArticlePropertiesModel = ArticleControlsPropertiesModel & ContentControlsPropertiesModel & HeaderControlsPropertiesModel & ListPageSettingsPropertiesModel & MainImageControlsPropertiesModel & SEocontrolsPropertiesModel & VisibilityControlsPropertiesModel;
