/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentModelBase } from './iApiContentModelBase';
import type { AuthorListPropertiesModel } from './authorListPropertiesModel';
import type { AuthorListContentModelContentType } from './authorListContentModelContentType';

export type AuthorListContentModel = Omit<IApiContentModelBase, 'contentType'> & {
  properties?: AuthorListPropertiesModel;
  contentType: AuthorListContentModelContentType;
};
