/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ArticleControlsContentResponseModel } from './articleControlsContentResponseModel';
import type { CategoryContentResponseModel } from './categoryContentResponseModel';
import type { ContactFormControlsContentResponseModel } from './contactFormControlsContentResponseModel';
import type { ContentControlsContentResponseModel } from './contentControlsContentResponseModel';
import type { FooterControlsContentResponseModel } from './footerControlsContentResponseModel';
import type { HeaderControlsContentResponseModel } from './headerControlsContentResponseModel';
import type { MainImageControlsContentResponseModel } from './mainImageControlsContentResponseModel';
import type { SEocontrolsContentResponseModel } from './sEocontrolsContentResponseModel';
import type { VisibilityControlsContentResponseModel } from './visibilityControlsContentResponseModel';
import type { HomeContentResponseModel } from './homeContentResponseModel';
import type { ArticleContentResponseModel } from './articleContentResponseModel';
import type { ArticleListContentResponseModel } from './articleListContentResponseModel';
import type { AuthorContentResponseModel } from './authorContentResponseModel';
import type { AuthorListContentResponseModel } from './authorListContentResponseModel';
import type { CategoryListContentResponseModel } from './categoryListContentResponseModel';
import type { ContactContentResponseModel } from './contactContentResponseModel';
import type { ContentContentResponseModel } from './contentContentResponseModel';
import type { ErrorContentResponseModel } from './errorContentResponseModel';
import type { SearchContentResponseModel } from './searchContentResponseModel';
import type { XMlsitemapContentResponseModel } from './xMlsitemapContentResponseModel';

export type IApiContentResponseModel = ArticleControlsContentResponseModel | CategoryContentResponseModel | ContactFormControlsContentResponseModel | ContentControlsContentResponseModel | FooterControlsContentResponseModel | HeaderControlsContentResponseModel | MainImageControlsContentResponseModel | SEocontrolsContentResponseModel | VisibilityControlsContentResponseModel | HomeContentResponseModel | ArticleContentResponseModel | ArticleListContentResponseModel | AuthorContentResponseModel | AuthorListContentResponseModel | CategoryListContentResponseModel | ContactContentResponseModel | ContentContentResponseModel | ErrorContentResponseModel | SearchContentResponseModel | XMlsitemapContentResponseModel;
