/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { MainImageControlsContentModel } from './mainImageControlsContentModel';
import type { MainImageControlsContentResponseModelContentType } from './mainImageControlsContentResponseModelContentType';

export type MainImageControlsContentResponseModel = Omit<IApiContentResponseModelBase & MainImageControlsContentModel, 'contentType'> & {
  contentType: MainImageControlsContentResponseModelContentType;
};
