/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { RichTextRowSettingsPropertiesModel } from './richTextRowSettingsPropertiesModel';
import type { RichTextRowSettingsElementModelContentType } from './richTextRowSettingsElementModelContentType';

export type RichTextRowSettingsElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: RichTextRowSettingsPropertiesModel;
  contentType: RichTextRowSettingsElementModelContentType;
};
